# Generated by Django 4.2.1 on 2023-05-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamer',
            name='operator',
            field=models.CharField(default='sam-test', max_length=20),
            preserve_default=False,
        ),
    ]
